DROP TABLE IF EXISTS student;
CREATE TABLE IF NOT EXISTS student
    (id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    first_name VARCHAR(255) NULL,
    last_name VARCHAR(255) NULL,
    email VARCHAR(255) NULL);